### ISSUE TITLE
im using burp version 23.2.2 and i installed the inql from bappstore but the tab was not showing

### ISSUE THREAD

**Issue by balook** [doyensec/inql#105]
![Screenshot_20230415_001810](https://user-images.githubusercontent.com/36122758/232131785-4ceda950-908d-4797-8592-1e95cb65d596.png)

**Comment by balook** [comment]
![errors](https://user-images.githubusercontent.com/36122758/232132223-d2ce221f-b919-47c0-8a46-18c04a2aec5e.png)

**Comment by execveat** [comment]
There will be a beta version of the 5.x release in a few days, it should fix this.

**Comment by execveat** [comment]
Closing the issue as v5.0 parses this schema fine, but feel free to reopen if there are still issues.

**Comment by execveat** [comment]
@balook I'm closing this issue as the new release should fix it. You can install it manually from here: https://github.com/doyensec/inql/releases/tag/v5.0.0 or wait until PortSwigger pushes the update through BApp Store.

Please reopen the issue if the problem persists.
