### ISSUE TITLE
Embed GraphiQL

### ISSUE THREAD

**Issue by execveat** [doyensec/inql#111]
Embed GraphiQL editor. It should be served from `http://inql/graphiql` address which should be transparently intercepted by InQL. GraphiQL itself only needs to add a session header, but otherwise it should function as is (meaning the target address should be the real server's address).

**Comment by ojensen5115** [comment]
This is the most important gap for me, and what I miss most acutely from 4.x. The Repeater tab is cool and all, but having the built-in autocompletion / schema magic of having a local GraphiQL that just appears whenever you need it is, to me, the 🎉-feature of this extension.

**Comment by execveat** [comment]
Thanks for the feedback! I'll start working on the next release soon and we should have GraphiQL & Co back by October, so stay tuned.

**Comment by lokiuox** [comment]
This feature is now complete in the dev branch
