### ISSUE TITLE
Introduce sessions

### ISSUE THREAD

**Issue by execveat** [doyensec/inql#112]
Introduce a session concept. A session should be associated with the particular scan result and the headers used during that scan. Session names should be predictable and easy to handle - this needs a bit of brainstorming. Tools proxying their traffic through Burp (including embedded tools such as GraphiQL) could use session by adding a special header `X-InQL-Session: session-name`, which would have the following impact:

- InQL should replace headers with the ones from the session (perhaps in the future we could add more functionality here, such as mixing headers or adding fancy logic like JWT auto-renewal)
- InQL should server introspection results locally, using the cached schema

**Comment by lokiuox** [comment]
Implemented in 777b339b4b18dfb1a798aaaeb1d2a464ec20c5e0
