### ISSUE TITLE
Kotlin Rewrite

### ISSUE THREAD

**Issue by lokiuox** [doyensec/inql#123]
The project's reliance on Jython makes it stuck on old technologies and difficult to maintain and improve. As the project grows bigger, the natural next step is moving toward a more modern language that will make the code structure more robust and organized. This will make it easier to understand and contribute to. This rewrite will be prioritized in order to get rid of the technical debt introduced by Jython as soon as possible and allow new features and bugfixes to be implemented directly in the new Kotlin version.

The initial goal will be to port everything that is currently implemented in Python except for the gqlspection library, for which we will introduce an interface that will allow it to be seamlessly replaced with a Java/Kotlin implementation at a later time. The rest of the code will be ported to Kotlin in almost a 1:1 way at first, but reorganizing/restructuring it where needed to be more in line with typical OO design patterns and generally more readable. Some of the planned new features may also be directly implemented during the rewrite if time permits.

**Comment by execveat** [comment]
The rewrite has been pushed to dev branch. Thank you @lokiuox!
