### ISSUE TITLE
Any Reason why Im getting Task: rebuildAltair FAILED

### ISSUE THREAD

**Issue by santikris2003** [doyensec/inql#128]
While build InQL jar file using ./gradlew getting this error 
./gradlew 

> Configure project :
Version from git tag: v5.0.2

> Task :rebuildAltair FAILED

> build
> mkdir -p build && cp -r node_modules/altair-static/build/dist/ build/ && cp -f index.html build/index.html

cp: node_modules/altair-static/build/dist/: No such file or directory

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rebuildAltair'.
> Process 'command 'npm'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 6s
3 actionable tasks: 2 executed, 1 up-to-date

**Comment by maimsing** [comment]
git checkout master

**Comment by execveat** [comment]
Yeah, the dev is broken right now, you need to run `npm install` manually a bunch of times. I'm looking into a way to parallelize that process as it takes 40 seconds right now. Please use master for now, roll back to a previous commit or install node dependencies manually.

**Comment by santikris2003** [comment]
I tried that getting this error now
git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
$ git submodule init
$ git submodule update
$ ./gradlew
Downloading https://services.gradle.org/distributions/gradle-8.0.2-bin.zip
...........10%............20%............30%............40%............50%............60%...........70%............80%............90%............100%

Welcome to Gradle 8.0.2!

Here are the highlights of this release:
 - Improvements to the Kotlin DSL
 - Fine-grained parallelism from the first build with configuration cache
 - Configurable Gradle user home cache cleanup

For more details see https://docs.gradle.org/8.0.2/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '/Users/*******/Downloads/inql/settings.gradle' (/Users/*******/.gradle/caches/8.0.2/scripts/65x4mf3si6pv31vxfmm9p556).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

**Comment by Recordatio** [comment]
I got the same error as @santikris2003 . Tried both from dev and master as well, same issue.

**Comment by santikris2003** [comment]
thanks for sharing the new set of instructions ,here's what I get when I execute those steps

$ task all
task: [Run all commands] task init
task: Task "Initializing git submodules" is up to date
task: [Run all commands] task deps
task: [Installing dependencies for playground] yarn install
task: [Installing dependencies for voyager] yarn install
task: [Installing dependencies for graphiql] yarn install
task: [Installing dependencies for altair] yarn install
yarn install v1.22.19
yarn install v1.22.19
yarn install v1.22.19
yarn install v1.22.19
warning package.json: No license field
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[1/4] 🔍  Resolving packages...
[1/4] 🔍  Resolving packages...
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[2/4] 🚚  Fetching packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.22.13.tgz: ENOENT: no such file or directory, open '/Users/santikris2003/Library/Caches/Yarn/v6/npm-@babel-code-frame-7.22.13-e3c1c099402598483b7a8c46a721d1038803755e-integrity/node_modules/@babel/code-frame/.yarn-tarball.tgz'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/santikris2003/Downloads/inql/lib/playground/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error An unexpected error occurred: "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.22.13.tgz: EINVAL: invalid argument, open '/Users/santikris2003/Library/Caches/Yarn/v6/npm-@babel-code-frame-7.22.13-e3c1c099402598483b7a8c46a721d1038803755e-integrity/node_modules/@babel/code-frame/.yarn-tarball.tgz'".
info If you think this is a bug, please open a bug report with the information provided in "/Users/santikris2003/Downloads/inql/lib/graphiql/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
✨  Done in 0.57s.
error https://registry.yarnpkg.com/caniuse-lite/-/caniuse-lite-1.0.30001538.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, stat '/Users/santikris2003/Library/Caches/Yarn/v6/npm-caniuse-lite-1.0.30001538-9dbc6b9af1ff06b5eb12350c2012b3af56744f3f-integrity/node_modules/caniuse-lite/data/regions/MS.js'"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
exit status 1
task: Failed to run task "all": exit status 1

**Comment by execveat** [comment]
I think you might be running out of the disk space? The node depedencies do take a lot of space - around 1GB in total.

**Comment by santikris2003** [comment]
I'm afraid not , I have 500+ GB of free space , not sure why Im getting this error

**Comment by execveat** [comment]
You probably need to nuke your node package cache, it seems broken. I can't replicate this issue whatsoever. Does it occur in other VMs / other environments? Please clean your environment, redownload InQL repo and try building again, just to make sure it's not due to previously cached artifacts:

```shell
git clone git@github.com:doyensec/inql.git; cd inql
git checkout dev
task all
```

**Comment by execveat** [comment]
Managed to replicate the error. Going into lib/* folders and running `yarn install` manually, then returning back to the project root and rerunning `task all` fixed it. I wonder what's going on, will debug this later.

**Comment by lokiuox** [comment]
I believe ffd37a01ce9fd2dd280a8556871d4b4bd0736df9 should have fixed this issue, closing this for now. Please reopen it if it still happens on the latest dev commit.
