### ISSUE TITLE
Integrate Schema Cycle Detection

### ISSUE THREAD

**Issue by flowirtz** [doyensec/inql#13]
One thing GraphQL is especially prone to is DOS attacks.

> A problem with GraphQL is that the freedom of creating customized requests allows data to be included several times in the response, growing the response’s size exponentially.

(["Detecting Cycles in GraphQL Schemas"](http://www.diva-portal.org/smash/get/diva2:1302887/FULLTEXT01.pdf), Lind and Soames, 2019)

The paper above is quite a good read. There are various measures to mitigate this issue (limiting query depth, [computing query cost](https://developer.github.com/v4/guides/resource-limitations/#calculating-nodes-in-a-call), ...).

You can find cycles quite easily via their tool: https://github.com/LiUGraphQL/graphql-schema-cycles.

Only toyed around with the webapp so far, but doesn't seem too hard to integrate.
Definitely a good one for this collection, imo.

**Comment by 1522402210** [comment]
@thypon  error

Detect arguments is ENABLED, known types will be replaced with placeholder values

**Comment by thypon** [comment]
implemented in https://github.com/doyensec/inql/releases/tag/v3.0.0
