### ISSUE TITLE
CORS Error in Web Editor

### ISSUE THREAD

**Issue by lokiuox** [doyensec/inql#133]
**Describe the bug**
Responses sent to web editor (GraphiQL, Voyager, etc) should be modified to inject CORS headers. At the moment this is already done on OPTIONS preflight requests, but from testing it looks like it's not enough and needs to be done on POST requests too.

**Comment by execveat** [comment]
Ah, makes sense. Yeah, we should handle all possible conditions in the same way.

**Comment by lokiuox** [comment]
Fixed in 3b21d47bdc530d4fe67c95777440d2976bf72221
