### ISSUE TITLE
GraphQL versions are iterated in the wrong order

### ISSUE THREAD

**Issue by execveat** [doyensec/inql#134]
We have multiple versions of GraphQL schemas in order to fall back to the most compatible. However, they are tried in the wrong order right now, starting with the oldest one.

I think the fix is as easy as reverting the iteration order in https://github.com/doyensec/inql/blob/dev/src/main/kotlin/inql/graphql/Introspection.kt#L23 , but please review this.

**Comment by lokiuox** [comment]
Done!
