### ISSUE TITLE
Where is inql_burp.py

### ISSUE THREAD

**Issue by 0-0eth0** [doyensec/inql#17]
HI,
There is no  file named `inql_burp.py` to use in burp.

Thanks

**Comment by thypon** [comment]
Hi there,

inql_burp.py extensions are compiled through the Makefile and will be released under https://github.com/doyensec/inql/releases . You can download the v1.0.0 release [here](https://github.com/doyensec/inql/releases/download/v1.0.0/inql_burp.py).

**Comment by 0-0eth0** [comment]
Hi there,
Thanks for your quick response,
I am sorry!

Regards,

**Comment by thypon** [comment]
I included the release link in the install steps.
Let me know if you have any other issue :)

https://github.com/doyensec/inql/commit/1d4f85d1807dd393d9cd0d60f3e048775b8c276e
