### ISSUE TITLE
Send to Repeater always greyed out

### ISSUE THREAD

**Issue by albinowax** [doyensec/inql#18]
First, this extension is really handy and I'd love to see it in the BApp store.

However, the 'Send to Repeater' option seems to be permanently greyed out. To replicate, paste in `https://hackerone.com/graphql` (or any other valid endpoint), click Load, and right click on any query template. I've tested on both windows and linux. I'm using Burp Suite Pro v2020.2.1.

It's such an obvious flaw I'm probably just doing something wrong.

**Comment by thypon** [comment]
<img width="1392" alt="Screen Shot 2020-04-15 at 18 12 39" src="https://user-images.githubusercontent.com/62013467/79360806-b63a5000-7f44-11ea-8f82-961ec5b31582.png">

"Send to Repeater" is greyed out until you navigate to pages using the graphql API.
What the extension tries to do is inferring the HTTP headers from previous valid graphql API calls.

**Comment by ikkisoft** [comment]
@albinowax I assume we can close the issue. If you could facilitate the integration in the BApp store, it would be awesome!

**Comment by albinowax** [comment]
I guess there's a bug that means it fails to recognise valid graphql calls in my case, ah well.

If you email support@portswigger.net saying you'd like to get it into the BApp store, they'll take care of it.

**Comment by thypon** [comment]
Hi there,

@albinowax I included a more seemless integration for send to repeater functionality.
Now it should work out of the box 99% of the cases.

It's live in `v1.1.1` https://github.com/doyensec/inql/releases/tag/v1.1.1 .

This is the fix I adopted https://github.com/doyensec/inql/commit/db2146ca955b839b9eb8dfabb3b9db2ae0d27a4b .
