### ISSUE TITLE
How to pass headers in --header

### ISSUE THREAD

**Issue by alimp5** [doyensec/inql#19]
Hi man

at first, thank you for this tool.

but how to add custom header(s) in inql tool !??
i tried a few ways but failed.
1: 
--header "{Key1:Val1, Key2:Val2, ........}"
2:
--header "Key1:Val1" --header "Key2:Val2" .................

how to set header !!!???
Tnx

**Comment by lean0x2F** [comment]
--header "HeaderName" "HeaderValue"

**Comment by thypon** [comment]
This issue seems to be solved!

Thanks @lean0x2F

**Comment by mrbiggleswirth** [comment]
> --header "HeaderName" "HeaderValue"

You are a scholar and a gentleman.
