### ISSUE TITLE
Burp Extension: Setting custom headers (e.g. auth)

### ISSUE THREAD

**Issue by lean0x2F** [doyensec/inql#20]
Hi!

Loving your tool so far, thank you 🙇 

I'm used to running this tool from the cli. When doing so, I would always set --headers in case a custom header such as an auth token is needed to do introspection (this is a common scenario). I haven't found a way to do that using the Burp extension. The only way to add a header is after a schema is loaded, which is pointless as I need a header to load the schema in the first place.

Am I missing something?

Thanks!

Leandro

**Comment by lean0x2F** [comment]
Below you can see that "Set Custom Header" is greyed out:

![image](https://user-images.githubusercontent.com/19156572/83715728-79194280-a604-11ea-9bc2-35c67b7565a4.png)

**Comment by thypon** [comment]
There are two kind of headers:

- **Custom Header(s)**, are headers needed to be added when you send the request through the repeater.
- **Load Header(s)** are instead the headers that are used within the introspection query on all the domain on which the introspection query is performed.

What you are searching for is **Load Header(s)** which are in a submenu available in the configure menu.
![CleanShot 2020-06-05 at 13 45 39](https://user-images.githubusercontent.com/581115/83873158-8b45ce80-a733-11ea-80b7-840670946a62.gif)

**Comment by thypon** [comment]
consider there is also the **Authorization Key** configuration which is more or less what you are searching for, without adding custom headers.

**Comment by lean0x2F** [comment]
Thank you so much ❤️

**Comment by thypon** [comment]
Thank you for the feedback. Let me know if you have any other issue, if the issues start to be repeated I may even consider changing a little bit the interface to be more intuitive for users.
