### ISSUE TITLE
InQL scanner not scanning the given url

### ISSUE THREAD

**Issue by DivisionSi** [doyensec/inql#21]
Hi,
I input my url, schemas and even the` https://anilist.co/graphiql` but as soon as I press the Enter key, nothing changes and the input fields clears, regardless of how long I wait.

I am using this extension in BurpSuite Community Edition v2020.5.

**Comment by thypon** [comment]
`https://anilist.co/graphiql` is the graphiql interface while usually `https://anilist.co/graphql` is the actual query endpoint. In order to the Scanner to work you need to input the query endpoint.

**Comment by DivisionSi** [comment]
I tried both, same behavior.

**Comment by thypon** [comment]
May

**Comment by DivisionSi** [comment]
Jython 2.7.2
java version "1.8.0_251"
OS Windows
![ezgif-4-9cf5c4540c05](https://user-images.githubusercontent.com/24440961/84426694-10058080-ac3d-11ea-9a22-75a6ed46118e.gif)

**Comment by thypon** [comment]
Ok, so, the introspection passes through the Burp proxy server by itself. You need to:

- Go to the Proxy Tab
- Press on "Intercept is On"
- Go back to the InQL Scanner

This thing is not needed if you disable interception from the beginning.

**Comment by DivisionSi** [comment]
Great! That solved it. Thanks :)
