### ISSUE TITLE
Question:  HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by shivshankarb** [doyensec/inql#25]
**Describe the bug**
It is rather a question to seek help for authentication. 
We would like to authenticate via inQL command line, but enable to do so.

**To Reproduce**
1. Authenticate with the keycloak instance, either via postman / browser etc, or via curl eg.
curl --data "grant_type=password&username=x&password=y&client_id=fcn-web" http://localhost:8080/auth/realms/FCN/protocol/openid-connect/token

We get response like: 
"access_token":XXXXXX",
"expires_in":300,
"refresh_expires_in":1800,
"refresh_token":"XXXX",
"token_type":"bearer",
"not-before-policy":1588264961,
"session_state":"XXXX",
"scope":"profile email"

2. Try to pass Authorization code ("access_token" received) via -k (API Authentication Key)
inql -t https://localhost/graphql -k XXX

3. Response is : [!] HTTP Error 401: Unauthorized

**Expected behavior**
Expecting to login

**Screenshots**

**Desktop (please complete the following information):**
inQL command line tool

**Additional context**

**Comment by thypon** [comment]
Hi,

Reading through https://github.com/doyensec/inql/blob/master/inql/introspection.py#L113 and your token response type you need to pass the token in the form:

```
inql -t https://localhost/graphql -k "Bearer XXXXXX"
```
