### ISSUE TITLE
Inql hangs on start when attemping to start with jython

### ISSUE THREAD

**Issue by dan-lind** [doyensec/inql#29]
**Describe the bug**
Inql hangs on start. When I start the java icon pops up in the task bar, and CPU usage for jython goes to ~120%. Then it stays there and nothing more happens. Installed running `jython -m pip install inql`
```
$ jython -m inql
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.io.StreamIO (file:/usr/local/Cellar/jython/2.7.2/libexec/jython.jar) to field java.io.FilterOutputStream.out
WARNING: Please consider reporting this to the maintainers of org.python.core.io.StreamIO
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Expected behavior**
InQL UI starts. 

**Screenshots**
Just to clarify, this is all I see
<img width="55" alt="Skärmavbild 2020-12-18 kl  06 29 40" src="https://user-images.githubusercontent.com/433464/102578451-7ee6f900-40fa-11eb-96d4-ca09e16cf5bf.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Java Version
```
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9)
OpenJDK 64-Bit Server VM (build 15.0.1+9, mixed mode, sharing)
```
- Python Version: 3.9

**Comment by thypon** [comment]
I'm trying to reproduce it without success.
It works for me with Catalina+Jython 2.7.2+Java 14.
Can you send me the jython version too?

**Comment by thypon** [comment]
I will try later with newer Java, even if it should not affect that.
One issue could be the new permission model with macOS:
if you run the tool from Desktop/Downloads or Documents folder
Java may not have rights to access and will hang the execution.

**Comment by dan-lind** [comment]
Works after a restart, I'll close this.
