### ISSUE TITLE
Load is broken

### ISSUE THREAD

**Issue by louissanchez84** [doyensec/inql#30]
Trying to load a json schema file and point to an known good graphQL path and neither is working. I see the documentation file in playground looks okay. No clue why this isn't working.

**Comment by louissanchez84** [comment]
Any ideas? I can share the file with you directly.

**Comment by louissanchez84** [comment]
I guess just close this out, I'll just have to find a different way to work with GraphQL.

**Comment by ikkisoft** [comment]
If you want, please upload a sanitize version of the json schema file or send it over to info@doyensec.com 

Having said that, we might not touch this issue for few weeks since we're busy with other stuff.

Thanks
