### ISSUE TITLE
Burp inQL Does not load the results

### ISSUE THREAD

**Issue by sssseossss** [doyensec/inql#36]
**Describe the bug**
Hi, thanks for the great extension. I have setup the required cookies via the load headers and URL and press enter. inQL launches the request, burp interception shows the request is as should be and the response contains all the expected response (parameters, objects etc.), However, the plugin dashboard is still empty - so I cannot review results and perform further actions.

**To Reproduce**
The extender output shows:
Quering GraphQL schema from: https://[obfuscated]/api/graph
Proxy ENABLED: localhost:8080
Detect arguments is ENABLED, known types will be replaced with placeholder values
HTTP/2
Quering GraphQL schema from: https://[obfuscated]/api/graphql
Proxy ENABLED: localhost:8080
Detect arguments is ENABLED, known types will be replaced with placeholder values
HTTP/2
Quering GraphQL schema from: https://[obfuscated]/api/graphql
Proxy ENABLED: localhost:8080
Detect arguments is ENABLED, known types will be replaced with placeholder values
HTTP/2
**Expected behavior**
Results should be demonstrated on screen.
**Screenshots**
Sending to repeater shows request/response as follows:
![image](https://user-images.githubusercontent.com/16890918/120459314-c0b1e600-c3a0-11eb-8b05-a90a23369045.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java Version: 
java version "15.0.1" 2020-10-20                                                                                        Java(TM) SE Runtime Environment (build 15.0.1+9-18)                                                                     Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)
- Python Version: Python 3.9.5
- Burp Version: 2021.5.1
 - Version: [e.g. 22]

**Additional context**
running the inQL cli from ubuntu provides me the json results fine.
Could you please assist in resolving this. Thanks a lot!

**Comment by thypon** [comment]
Hi there, `HTTP/2` error seems to indicate that you are using the version included within the Burp Store.
This bug has already been addressed in the latest InQL version available at https://github.com/doyensec/inql/releases/tag/v4.0.1 .

Jython latest does not support HTTP/2 at the moment, so you may use the latest version or disable HTTP/2 manually in the burp preferences.
