### ISSUE TITLE
Cannot install standalone UI on OSX

### ISSUE THREAD

**Issue by severin** [doyensec/inql#37]
**Describe the bug**

```
jython -m pip install inql                                                                           
DEPRECATION: A future version of pip will drop support for Python 2.7.
Collecting inql
  ERROR: Could not find a version that satisfies the requirement inql (from versions: none)
ERROR: No matching distribution found for inql
```

**To Reproduce**

1. Install *jython* via homebrew
2. Verify *jython* works: `jython --version` -> `Jython 2.7.2`
3. Attempt to install inql as per the README: `jython -m pip install inql` -> Results in the error mentioned above

**Expected behavior**

Successful installation of standalone inql

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Java Version: openjdk 16.0.1 2021-04-20 / OpenJDK Runtime Environment Homebrew (build 16.0.1+0)
 - Python Version: Jython 2.7.2 / Python 2.7.16

**Comment by thypon** [comment]
Unfortunately this is a bug in jython. It seems like installing any package in pip will fail.
As an example you can try installing requests with `jython -m pip install requests`, and it will fail in a similar fashion.

My guess is that HTTP/2 is broken on jython and pypi switched to that recently.

![Screen Shot 2021-06-15 at 12 31 31](https://user-images.githubusercontent.com/581115/122038195-a3840b00-cdd5-11eb-8346-d7e292d02578.png)

**Comment by thypon** [comment]
As a temporary workaround you can still download the git project and start it without using pip in this way.

```
git clone https://github.com/doyensec/inql
cd inql
jython -m inql
```

**Comment by thypon** [comment]
Updated the readme with the new jython install procedure.
