### ISSUE TITLE
Can't delete data from inql scanner tab on burp

### ISSUE THREAD

**Issue by gprime31** [doyensec/inql#38]
delete dosen't work, am i missing something? where is the data stored so i can delete it? (linux)
thanks, best graphql tool out there :)

**Comment by thypon** [comment]
The data is stored in a temporary directory, which is reported in burp extender logs. It should either be deleted on extension unload, burp closing, or system reboot.

To be noted that deleting data **during** InQL execution is not supported.

**Comment by gprime31** [comment]
ya, none of that works, when burp is started the /tmp folder is created with all the info still in it, any ideas?

**Comment by gprime31** [comment]
got it only way was to right click and reset one by one in configure inql.
![2021-06-18_07-13](https://user-images.githubusercontent.com/44535257/122552882-df50e780-d004-11eb-9391-9558398fb06a.png)
