### ISSUE TITLE
Not able to install inql

### ISSUE THREAD

**Issue by santhosh12992** [doyensec/inql#39]
`jython -m pip install inql
DEPRECATION: A future version of pip will drop support for Python 2.7.
Collecting inql
  ERROR: Could not find a version that satisfies the requirement inql (from versions: none)
ERROR: No matching distribution found for inql
`
`smuralik@smuralik-NUC8i7BEH:~$ python -V
Python 2.7.18
`

**Comment by thypon** [comment]
Duplicate. This is due to a bug in jython, which is not able to install from pip packages anymore.
Fixing this bug is out of reach for this project.

**Comment by thypon** [comment]
https://github.com/doyensec/inql/issues/37
