### ISSUE TITLE
The latest version of inql_burp.py loaded in burpsuite will report an error

### ISSUE THREAD

**Issue by anbol** [doyensec/inql#42]
![image](https://user-images.githubusercontent.com/45890880/133868878-5ef8670b-29b1-4a75-9a45-4b7bf42df70f.png)

**Comment by thypon** [comment]
Please provide the information required to triage this bug as advised in the bug report template.
https://github.com/doyensec/inql/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
