### ISSUE TITLE
Discard Report for 'Exposed GraphQL Development Console' if response is 404

### ISSUE THREAD

**Issue by notdodo** [doyensec/inql#43]
**Describe the bug**
Do not report a 'Exposed GraphQL Development Console' low issue in Burp if the server responds with a 404

**To Reproduce**
1. Go to any website
2. Request to `/graphiql`
3. See error on Burp even if the server responds with a 404

**Expected behavior**
Do not report the issue

**Screenshots**

Request:
![Screenshot_20210927_110704](https://user-images.githubusercontent.com/6991986/134878762-416349db-2091-4164-b419-a26dbf943562.png)

Response:
![Screenshot_20210927_110737](https://user-images.githubusercontent.com/6991986/134878986-662c3020-64f9-4463-be55-0ea67c6e9b78.png)

Issue:
![Screenshot_20210927_110854](https://user-images.githubusercontent.com/6991986/134879060-13864731-b4f8-4bd7-8915-e7b9c910dea0.png)

**Desktop (please complete the following information):**
- OS: Ubuntu Linux 20.04
- Java Version: openjdk 11.0.11
- Python Version: 3.8.10
- Burp Version: 2021.8.3
- Version: 4.0.5

**Comment by execveat** [comment]
404 and other useless status codes are filtered properly and don't produce false positive findings.
