### ISSUE TITLE
Move "Setup Load Headers" Setting in General Configuration

### ISSUE THREAD

**Issue by ikkisoft** [doyensec/inql#44]
At the moment, it is possible to set an "Authorization Key" that allows setting a standard HTTP Authorization header (Basic, Bearer)

![Screen Shot 2021-10-07 at 10 19 21](https://user-images.githubusercontent.com/6027823/136346945-63c32fb1-49ae-4915-84e1-d268244198e5.png)

Many GraphQL services use cookies or customer headers for authentication. This is not currently supported by InQL. It would be great to extend the configuration and allow settings arbitrary headers. For instance, we can allow users to set arbitrary _headers:values_ that will be appended to all requests.

**Comment by thypon** [comment]
The feature should already be there as a sub-menu of the main configuration menu under "Setup Load Headers".
