### ISSUE TITLE
Disabling HTTP/2 Error

### ISSUE THREAD

**Issue by irsdl** [doyensec/inql#48]
**Describe the bug**
It shows the following error upon loading the extension:

```
Cannot disable HTTP/2! invalid literal for int() with base 10: '10.3'
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java Version: 15.0.1+9-18
 - Python Version: Jython v2.7.2
 - Burp Version: burpsuite_pro_v2021.10.3
 - Version: Latest BApp Store Version

**Comment by thypon** [comment]
Thanks for the report!

While I should fix the version handler, `inql` should work fine with HTTP/2, at the moment.

**Comment by bylkainj** [comment]
Hi
how can i fix this ?
Cannot disable HTTP/2! invalid literal for int() with base 10: '5.1'

**Comment by thypon** [comment]
> Hi how can i fix this ? Cannot disable HTTP/2! invalid literal for int() with base 10: '5.1'

No fix required, it's just an informative error at the current stage.
