### ISSUE TITLE
No inql output from loaded schema

### ISSUE THREAD

**Issue by Skrotrot** [doyensec/inql#53]
Hi,
I have trying to load a graphql schema but there is no output. In the extender tab I see this.

InQL Scanner Started! (tmpdir: /private/var/folders/5g/4dbw14jd3rd_rv7_bjggfcqm0000gn/T/tmpp4Y8U0 )
Cannot disable HTTP/2! invalid literal for int() with base 10: '3.9'
Loading JSON schema from: /Users/....../Documents/....../schema.json
Proxy ENABLED: localhost:8080
Parsing local schema file
Writing Introspection Schema JSON
DONE
Writing HTML Documentation

There are no errors. I am using an m1 macbook air on macOS Monterey.
[schema.txt](https://github.com/doyensec/inql/files/8892902/schema.txt)

**Comment by thypon** [comment]
Attaching the schema here may help debug the issue here :)

**Comment by Skrotrot** [comment]
Of course! I edited the original comment but it didn't allow json files so I put it as a txt file instead

**Comment by harmeet-1337** [comment]
I also have same issue and OS m1 macbook with macOS Monterey.

URL or local schema does not seem to load and logs show following:

```
Loading JSON schema from: /Users/MYUSER/Downloads/introspectionSchema.json
Proxy ENABLED: localhost:8080
Parsing local schema file
Detect arguments is ENABLED, known types will be replaced with placeholder values
Writing HTML Documentation

```

**Comment by thypon** [comment]
The issue above has already been solved and it's ready to be merged in the PR above. Cc @ikkisoft for more support.
