### ISSUE TITLE
All installation failed but have to go with pip install

### ISSUE THREAD

**Issue by A1vinSmith** [doyensec/inql#55]
**Describe the bug**
ModuleNotFoundError: No module named 'inql'

**To Reproduce**
1. pip3 install -r requirements.txt no errors
2. jython install it failed
3. run standalone cli failed too

**Expected behavior**
I'm little confused tho.

**Desktop (please complete the following information):**
 - OS: Linux Kali 5.18.0-kali5-amd64 x86_64
- Python Version: [e.g. Jython v2.7.2-DEV/Python 3.10.5]

**Additional context**

**Comment by thypon** [comment]
Hi, standard pip3 will install the modules in the python3 executables directory. Instead it's enough to move in the repo directory, after download and execute 'jython -m InQL'

**Comment by A1vinSmith** [comment]
will try that, thank you!
