### ISSUE TITLE
Display comments from the GraphQL schema

### ISSUE THREAD

**Issue by execveat** [doyensec/inql#70]
GraphQL schema can include descriptive comments which get displayed in GraphiQL, but not InQL. It's not immediately clear how to show them - inline, as a mousover, etc. But having this functionality would be very useful.

**Comment by thypon** [comment]
the intermediate representation is dropping these, I think. We may want to include them there too.

**Comment by execveat** [comment]
We could also add additional comments, for example to indicate complex types.

**Comment by execveat** [comment]
Moved to GQLSpection: https://github.com/doyensec/GQLSpection/issues/23
